### ISSUE TITLE
falguard doesn't support .yml files

### ISSUE THREAD

**Issue by matee911** [gwaramadze/falguard#1]
Drogi Remy,

I would like to add .yaml support to falguard, may I?

**Comment by gwaramadze** [comment]
Sure, go for it!

**Comment by TomFaulkner** [comment]
Did this happen? Rather than open the file, why not receive the dict?

**Comment by gwaramadze** [comment]
I don't think it did.

**Comment by zekth** [comment]
This can be closed now @gwaramadze .

**Comment by gwaramadze** [comment]
Yup, I have just released new version. Good job! Thanks a lot.
