### ISSUE TITLE
Shouldn't faguard return 405 method not allowed instead of 404 when url exists?

### ISSUE THREAD

**Issue by rtxm** [gwaramadze/falguard#2]
Thank you for *Falguard*, it is very useful.

I have a question: Say I have a resource published on `/hello` that only implement `on_get`. 

If I try to access it with a POST request, *Falguard* returns a 404 error, whereas it should be a 405, shouldn't it ?

**Comment by gwaramadze** [comment]
Hey, thanks, great to hear that you like it!

Your requirement seems quite legitimate, but I don't think I will have time to implement it or anything else in the Falguard. At least not in the coming weeks. Maybe you could give it a shot?

**Comment by gwaramadze** [comment]
@rtxm Once again, thx for your contribution. I have just made some tuning of he repository and released your change to pypi. Cheers.
